### ISSUE TITLE
Use Dialog service to get Date

### ISSUE THREAD

**Issue by tur-ing** [watson-developer-cloud/movieapp-dialog#16]
How can I use the Watson Dialog service to retrieve a date, like February 18th 2016?

**Comment by mitchmason** [comment]
you should post these on the dW forums in the future to make sure we get them answered quickly.
https://developer.ibm.com/answers/questions/ask/?topics=dialog
that link will automatically tag with dialog, fyi

To answer your question you would use entities. We have developed language packs which include what are known as system entities. These are pre-defined by our team because they are common and we want to avoid everyone re-developing the same entities when we can do it once for you. These are not yet documented though, and will be shortly with a list of all system entities.

For now, you should be able to use them without the documentation. Use the entity (DATE_TIME_RANGE) and it can capture, dates, times, etc. and will all be broken down as meta data, see the tutorial on capturing entities as profile variables for more info there.

Alternatively, if you wanted to create your own, you could either create a single entity for every day of every month of every year (this would take forever!) or create a few different ones.
One for month, one for day, and one for year.
Then write a rule for something like
(MONTH) (DAY) (YEAR) to capture them each individually. This would be fairly simple for you to do all on your own, but I would definitely advise using the system entity, and keep your eye on the documentation for when we publish all of them.

**Comment by tur-ing** [comment]
OK, thank you for the fast reply. I am going to try your suggestion
